### ISSUE TITLE
De-Lombok the project

### ISSUE THREAD

**Issue by gsdatta** [OpenAPITools/openapi-diff#174]
Hi, would you be open to using delombok (either at build time or on the entire codebase) from this project? Lombok makes it incompatible with Kotlin (see https://stackoverflow.com/questions/35517325/kotlin-doesnt-see-java-lombok-accessors/35530223#35530223) from the Kotlin team.

Lombok provides already a de-lombok tool https://projectlombok.org/features/delombok that could be used for this, which would then make it compatible with Kotlin.

**Comment by quen2404** [comment]
Hi @gsdatta, lombok was using to simplify development. But if this tool is problematic for Kotlin users, we can remove it :)

**Comment by gsdatta** [comment]
Thanks @quen2404!

**Comment by joschi** [comment]
> Lombok makes it incompatible with Kotlin

@gsdatta Wouldn't this only affect you if you wanted to use the annotated POJOs as source files in your project? It should work without a problem if you're using `org.openapitools.openapidiff:openapi-diff-core` as a dependency in your projects.

Did you run into the problem you've described with `openapi-diff`?

**Comment by joschi** [comment]
@gsdatta Any additional input?

**Comment by hiddewie** [comment]
I think I ran into this problem today in Kotlin when deserializing a full `ChangedOpenApi` object which is exposed over HTTP as JSON. There is no contructor available, which would normally be added by Lombok (`@Data`).

Using Spring Boot 2.3, Jackson Serialization (with Kotlin support).

Example test case:
```
        webClient.post()
            .uri("/diff")
            .bodyValue(diffRequest)
            .exchange()
            .expectStatus().is2xxSuccessful
            .returnResult(ChangedOpenApi::class.java)
            .responseBody
            .blockFirst()!! // Fail with NullPointer if there is no response
```

Example test output:
```
xxxxxxxxxxxxxxx.OpenApiDiffTest > Diff changed summary() FAILED                                                                                                               
    org.springframework.core.codec.CodecException: Type definition error: [simple type, class com.qdesrame.openapi.diff.core.model.ChangedOperation]; nested exception is com.fasterx
ml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.qdesrame.openapi.diff.core.model.ChangedOperation` (no Creators, like default constructor, exis
t): cannot deserialize from Object value (no delegate- or property-based Creator)                                                                                                    
     at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.qdesrame.openapi.diff.core.model.ChangedOpenApi["changedOperations"]->java.util.ArrayList[0])          
        at org.springframework.http.codec.json.AbstractJackson2Decoder.processException(AbstractJackson2Decoder.java:211)                                                            
                                                                                                                                                                                     
        Caused by:                                                                                                                                                                   
        com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.qdesrame.openapi.diff.core.model.ChangedOperation` (no Creators, like defaul
t constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)                                                                                 
         at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.qdesrame.openapi.diff.core.model.ChangedOpenApi["changedOperations"]->java.util.ArrayList[0])      
            at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)                                                                
            at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1615)                                                           
            at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)                                                                          
            at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1077)                                                     
            at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1332)                                        
            at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)                                                                
            at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)                                                                          
```
