### ISSUE TITLE
Local working dir used in relative paths

### ISSUE THREAD

**Issue by D0rmouse** [OpenAPITools/openapi-diff#226]
I'm trying to run a openapi-diff between the HEAD and latest tag in a repository. My api specs are split up in several files that are referenced using `$ref`. 

I've checked out the latest tag in build/vorigeTag and the HEAD is in the current directory. When I run `openapi-diff build/vorigeTag/specs/stamgegevens.json specs/stamgegevens.json`, I get this output: 

```
D:\dev\projects\stamgegevens-spec>npm run openapi-diff -- build/vorigeTag/specs/stamgegevens.json specs/stamgegevens.json

> stamgegevens-spec@1.0.0 openapi-diff D:\dev\projects\stamgegevens-spec
> openapi-diff "build/vorigeTag/specs/stamgegevens.json" "specs/stamgegevens.json"

OpenApiDiffErrorImpl [VError]: Validation errors in "build/vorigeTag/specs/stamgegevens.json": Error opening file "D:\dev\projects\stamgegevens-spec\paths\activiteitsoorten.json"
ENOENT: no such file or directory, open 'D:\dev\projects\stamgegevens-spec\paths\activiteitsoorten.json'
    at D:\dev\projects\stamgegevens-spec\node_modules\openapi-diff\dist\openapi-diff\spec-parser\common\validate-and-dereference-spec.js:23:15
    at Generator.throw (<anonymous>)
    at rejected (D:\dev\projects\stamgegevens-spec\node_modules\openapi-diff\dist\openapi-diff\spec-parser\common\validate-and-dereference-spec.js:6:65) {
  jse_shortmsg: 'Validation errors in "build/vorigeTag/specs/stamgegevens.json"',
  jse_cause: {
    stack: 'ResolverError: Error opening file "D:\\dev\\projects\\stamgegevens-spec\\paths\\activiteitsoorten.json" \n' +
      "ENOENT: no such file or directory, open 'D:\\dev\\projects\\stamgegevens-spec\\paths\\activiteitsoorten.json'\n" +
      '    at ReadFileContext.callback (D:\\dev\\projects\\stamgegevens-spec\\node_modules\\@apidevtools\\json-schema-ref-parser\\lib\\resolvers\\file.js:52:20)\n' +
      '    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)',
    code: 'ERESOLVER',
    message: 'Error opening file "D:\\dev\\projects\\stamgegevens-spec\\paths\\activiteitsoorten.json" \n' +
      "ENOENT: no such file or directory, open 'D:\\dev\\projects\\stamgegevens-spec\\paths\\activiteitsoorten.json'",
    source: 'D:\\dev\\projects\\stamgegevens-spec\\paths\\activiteitsoorten.json',
    path: null,
    toJSON: [Function: toJSON],
    ioErrorCode: 'ENOENT',
    name: 'ResolverError',
    toString: [Function: toString]
  },
  jse_info: {},
  code: 'OPENAPI_DIFF_PARSE_ERROR'
}
```

So this leads to the conclusion that open-api diff is using the relative paths in my openapi specs (like `"$ref": "./paths/activiteitsoorten.json#/activiteitsoorten"`) relative to the current working directory instead of relative to the current file. 

It should refer top D:\dev\projects\stamgegevens-spec\\**build**\\**vorigeTag**\\**specs**\paths\activiteitsoorten.json instead of failing on the fact that D:\dev\projects\stamgegevens-spec\paths\activiteitsoorten.json cannot be found.

Is this something that can be fixed?

**Comment by joschi** [comment]
@D0rmouse The npm package [openapi-diff](https://www.npmjs.com/package/openapi-diff) is a different project.

Please report the issue at https://bitbucket.org/atlassian/openapi-diff.

**Comment by D0rmouse** [comment]
Ah my bad, thanks for the headsup.

**Comment by joschi** [comment]
@D0rmouse No worries and good luck with your issue! 😄
