### ISSUE TITLE
Allowing circular references

### ISSUE THREAD

**Issue by alexandreczg** [OpenAPITools/openapi-diff#542]
Is there a way to generate the report allowing for circular dependencies on the parameters?

```
OpenApiDiffErrorImpl [VError]: ReferenceError: Circular $ref pointer found at /builds/#/components/schemas/Content/properties/children/items
    at /usr/local/lib/node_modules/openapi-diff/dist/openapi-diff/spec-differ/diff-finder/json-schema-diff.js:27:15
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/openapi-diff/dist/openapi-diff/spec-differ/diff-finder/json-schema-diff.js:6:65) {
  jse_shortmsg: 'ReferenceError: Circular $ref pointer found at /builds/#/components/schemas/Content/properties/children/items',
  jse_info: {},
  code: 'OPENAPI_DIFF_DIFF_ERROR'
}
```

Thank you!

**Comment by joschi** [comment]
@alexandreczg You're using a different openapi-diff than this project. 😉 

➡️ https://github.com/Azure/openapi-diff
